#!/bin/bash

#clean dbname xtime

psql -tc "delete from files where exists (select * from files as alias where alias.path=files.path and alias.xtime<$2 and alias.xtime>files.xtime);" "$1"
psql -tc "delete from files where not exists (select * from files as alias where alias.path=files.path and device is not null);" "$1"
psql -tc "delete from files where device is null and xtime=(select min(xtime) from files as alias where alias.path=files.path);" "$1"
psql -tc "delete from inodes where not exists (select * from files where files.device=inodes.device and files.inode=inodes.inode and files.ctime=inodes.ctime)" "$1"

#IN GOD WE TRVST.
