#!/bin/bash

USE="verity_content_diff 'db conn string' tree0 tree0_as-of_time_t tree1 tree1_as-of_time_t"

DIR=/usr/local/lib/verity

if [ $# -ne 5 ]; then echo "$USE" >&2; exit 1; fi

if [ $3 -lt $5 ]; then f=$5; else f=$3; fi

$DIR/list_hmacs -p "$2" -t $3 "$1" | sort -u > /tmp/$$.l
$DIR/list_hmacs -p "$4" -t $5 "$1" | sort -u > /tmp/$$.r
diff /tmp/$$.l /tmp/$$.r > /tmp/$$.diff
rm /tmp/$$.l
rm /tmp/$$.r
while IFS= read -r -d '' line; do
	echo -n "<$line"
	echo -ne \\0
	done < <(grep --mmap '^<' /tmp/$$.diff | cut -c 3- | $DIR/paths_of_hmacs -s -p "$2" -t $f "$1") 
while IFS= read -r -d '' line; do
	echo -n ">$line"
	echo -ne \\0
	done < <(grep --mmap '^>' /tmp/$$.diff | cut -c 3- | $DIR/paths_of_hmacs -s -p "$4" -t $f "$1")
rm /tmp/$$.diff

#IN GOD WE TRVST.
