#!/bin/bash

USE="verity_diff <(list -c ... | grep ...) <(list -c ... | grep ...)"

mkdir /tmp/$$
IFS='
'

left="/tmp/$$/left"; sort -z "$1" > "$left"
right="/tmp/$$/right"; sort -z "$2" > "$right"

parse_list () {
	while	IFS= read -r -d '' line; do
		echo ${line:0:64} >> "$2"
		done < "$1"; }

parse_list "$left" /tmp/$$/left.hashes
parse_list "$right" /tmp/$$/right.hashes

for line in `diff /tmp/$$/left.hashes /tmp/$$/right.hashes`; do
	hash=`echo $line | cut -c 3-`
	sign=${line:0:1}
	if [ "$sign" != '<' -a "$sign" != '>' ]; then continue; fi
	echo -n "$sign"
	if	[ "$sign" = '<' ]
		then grep -z "^$hash" "$left"
		else grep -z "^$hash" "$right"; fi
	done

#rm -rf /tmp/$$

#IN GOD WE TRVST.
